                <div class="inputs d-flex justify-content-center">
                    <h3>Filtra per voto</h3>
                    <form class="form-check d-flex align-items-center">
                        <div>
                            <input type="number" step="1" min="0" name="vote" class="form-control" placeholder="Voto">
                        </div>
                        <div class="form-check form-switch px-5">
                            <input class="form-check-input" type="checkbox" id="parking" name="parking">
                            <label class="form-check-label" for="parking">Con parcheggio</label>
                        </div>
                        <button class="btn btn-primary">Cerca</button>
                        <a class="btn btn-secondary ms-2" href="index.php">Reset</a>
                    </form>
                </div>